### PR TITLE
adding auto import for better intellij support + gitignore

### PR DESCRIPTION
**Pull request by katrinsharp**
The line added to build.sbt allows to use intellij import capabilities. Without  this line, the latest intellij doesn't recognize the cross project. gitignore is added for ignoring intellij related files.

### CODE REVIEW

**Comment by sjrd** [comment]
Thanks.

First, don't change `.gitignore`. The sbt-specific stuff is already good (i.e., only `target/`). For IDE-specific stuff, this should be part of the global `.gitignore` of your local setup. It must not be part of a project's `.gitignore`.

For the change in `build.sbt`, this is clearly working around a bug of the IntelliJ import feature. Can we have an issue on file in IntelliJ's bug tracker, and a comment above that line referencing this filed bug?

**Comment by sjrd** [comment]
Also, format the commit message like this:

> Add an explicit import of autoImport to workaround an IntelliJ bug.
>
> See http://url/towards-filed-bug

Post a comment after you've updated the PR, so that I'm notified that something happened.

**Comment by katrinsharp** [comment]
First, *should* is a bit opinionated, but it is definitely up to the repo author to decide regarding the style. .gitignore is gone.
Second, I've submitted bug report added the its id to the pull request and the code. Not sure it's publicly accessible so far. If you know better way to submit a bug to jetbrains please let me know.

**Comment by zlangbert** [comment]
I'm not able to access the bug report but I'm on the latest intellij/scala plugin EAP and I can import this project fine.

Just tried with Intellij 14 and the stable scala plugin and it worked as well

**Comment by katrinsharp** [comment]
What is your version @zlangbert ? Mine claims to be the latest.
screen shot 2015-07-20 at 4 46 54 pm 2

**Comment by zlangbert** [comment]
@katrinsharp 

I'm on 141.1532. Also

> If you know better way to submit a bug to jetbrains please let me know. 

https://youtrack.jetbrains.com/issues/SCL. That's where I've submitted intellij bugs before

**Comment by sjrd** [comment]
From a discussion on the Gitter chat so far (https://gitter.im/scala-js/scala-js), it seems you are the only one experiencing this issue. It might be a problem in the local config. I'd like to see one other report that this is necessary before merging this, if you don't mind.

**Comment by katrinsharp** [comment]
Sure. I'll also ask around, maybe someone else experienced the same. Jetbrains suggested to try intellij 15.

**Comment by zlangbert** [comment]
So I just ran into this issue on IntelliJ 14 once, and the change in this PR fixed it. But then I `rm -r .idea` and re-imported and it worked (idk). So this issue does exist in IntelliJ 14. IMO this should probably be merged at least until IntelliJ 15 is released.

**Pull request closed without merging**
